### PR TITLE
fix: Update links in README.md

### PR DESCRIPTION
**Pull request by hermanschaaf**
Updates a few broken links in the readme.

Aside from this, it would also be great if we can publish the first release so that this repo can be used from a CloudQuery config :)

### CODE REVIEW

**Comment by hermanschaaf** [comment]
CC @jamesliupenn if you don't mind taking a look at this 🙇

**Review by 0xsemaj — APPROVED** [review]

**Comment by 0xsemaj** [comment]
@hermanschaaf can you elaborate on the release part? How do we allow CloudQuery configs to access to this repo?

**Comment by hermanschaaf** [comment]
@jamesliupenn I think all you need to do is push a tag (e.g. `v1.0.0` in this case), which will let the [release build](https://github.com/onfleet/cq-source-onfleet/blob/master/.github/workflows/release.yaml) run and release the first version.

**Comment by 0xsemaj** [comment]
Done, v1.0.0 released

**Pull request merged**
