### PR TITLE
feat: Upgrade to SDK v4

### PR DESCRIPTION
**Pull request by maaarcelino**
Hi there! This is a PR to update to our latest SDK! We are also rolling out hub shortly - https://hub.cloudquery.io/ so, once this PR is approved we can follow-up with additional PR so publish the plugin to our hub so users can enjoy dynamic searchable documentation for all versions and all tables.

I was unable to test the code as I don't have an API key and the signup for on your site appears broken (it keeps asking for a captcha which isn't displayed anywhere). Could you create a test API key for me so I can run the tests? My email is marcel@cloudquery.io. Once this is tested we can move forward with the upgrade.

### CODE REVIEW

**Comment by maaarcelino** [comment]
CC @jamesliupenn

**Comment by maaarcelino** [comment]
I received access to a test account and was able to test the changes. The PR is ready for review @jamesliupenn.

**Review by 0xsemaj — APPROVED** [review]
I'm not familiar with the v4 SDK but everything looks kosher from a birds-eye view

**Comment by maaarcelino** [comment]
@jamesliupenn I've updated the github workflow that was failing. Can you please rerun it and merge the PR if it's green?

The SDK upgrade introduces a lot of new options for controlling the memory usage and job scheduling of syncs. Currently your plugin uses all the default logic we have baked under the hood. The cool thing is that we will now publish your plugin on our Hub for other users to see.

I've created a team for you on our Hub. Can you give me an email address for you/someone on your side so I can transfer the ownership? You can share it here or email me at [marcel@cloudquery.io](mailto:marcel@cloudquery.io).

**Comment by 0xsemaj** [comment]
@maaarcelino can you send the ownership to integrations@onfleet.com

**Comment by maaarcelino** [comment]
@jamesliupenn I've sent you an invite and I've fixed the PR so it should pass now. Can you run the workflow and merge?

**Pull request merged**
